const firstName = [
  'Wil',
  'Scott',
  'Rediet',
  'Hal',
  'Serge',
  'Samson',
  'Leonard',
  'Manindra',
  'Luis',
  'Alfred',
  'Frances',
  'Gene',
  'David',
  'Lisa',
  'Andrew',
  'Cecilia',
  'Bruce',
  'Sanjeev',
  'Winifred "Tim"',
  'John Vincent',
  'Shakuntala',
  'Charles',
];
const lastName = [
  'van der Aalst',
  'Aaronson',
  'Abebe',
  'Abelson',
  'Abiteboul',
  'Abramsky',
  'Adleman',
  'Agrawal',
  'von Ahn',
  'Aho',
  'E. Allen',
  'Amdahl',
  'P. Anderson',
  'Anthony',
  'Appel',
  'R. Aragon',
  'Arden',
  'Arora',
  'Alice Asprey',
  'Atanasoff',
  'Atre',
  'Babbage',
];
const titles = [
  'business process management, process mining, Petri nets',
  'quantum computing and complexity theory',
  'algorithms, artificial intelligence',
  'intersection of computing and teaching',
  'database theory',
  'game semantics',
  'RSA, DNA computing',
  'polynomial-time primality testing',
  'human-based computation',
  'compilers book, the "a" in AWK',
  'compiler optimization',
  'supercomputer developer',
  'volunteer computing',
  'natural user interfaces',
  'compiler of text books',
  'invented treap, human-centered data science',
  'programming language compilers',
  'PCP theorem',
  'established the computer science curriculum at Vassar College',
  'computer pioneer',
  'database theory',
  'known for Integrated Data Store',
];
const words = [
  'This',
  'is',
  'a',
  'list',
  'of',
  'computer',
  'scientists',
  'people',
  'who',
  'do',
  'work',
  'in',
  'computer',
  'science',
  'in',
  'particular',
  'researchers',
  'and',
  'authors',
  'Some',
  'persons',
  'notable',
  'as',
  'programmers',
  'are',
  'included',
  'here',
  'because',
  'they',
  'work',
  'in',
  'research',
  'as',
  'well',
  'as',
  'program',
  'A',
  'few',
  'of',
  'these',
  'people',
  'pre-date',
  'the',
  'invention',
  'of',
  'the',
  'digital',
  'computer',
  'they',
  'are',
  'now',
  'regarded',
  'as',
  'computer',
  'scientists',
  'because',
  'their',
  'work',
  'can',
  'be',
  'seen',
  'as',
  'leading',
  'to',
  'the',
  'invention',
  'of',
  'the',
  'computer',
  'Others',
  'are',
  'mathematicians',
  'whose',
  'work',
  'falls',
  'within',
  'what',
  'would',
  'now',
  'be',
  'called',
  'theoretical',
  'computer',
  'science',
  'such',
  'as',
  'complexity',
  'theory',
  'and',
  'algorithmic',
  'information',
  'theory',
];

module.exports = {
  firstName,
  lastName,
  titles,
  words,
};
